[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
  ".", "src"]

[project]
# ...
dependencies = [
  "fastapi>=0.110",
  "uvicorn>=0.23",
  "requests>=2.31",
  "pydantic>=2.0",]
